### ISSUE TITLE
Is there a guide to use this on self hosting?

### ISSUE THREAD

**Issue by sharu725** [55sketch/gsx2json#1]
Is there a guide to use this on self hosting?

**Comment by VirenMohindra** [comment]
Did you even glance at the `README.md`? You install the app along with the dependencies with `npm install` and then run the app with `node app`. I don't think it can be more simple. If you do not have node/ npm download and follow the instructions for your specific OS by googling it.

After running the above commands you'll see output on your terminal - 
`GSX2JSON listening on port 5000`

which means GSX2JSON defaults to port 5000, which can be changed.

Depending on where you host it you can target the endpoint with 

`http://localhost:5000/api?id==SPREADSHEET_ID&sheet=SHEET_NUMBER`

... or whatever your server ip address is where you host it respectively.

Good luck!

**Comment by usfslk** [comment]
The app crash if wrong ID provided, I think handling that would be great

**Comment by 55sketch** [comment]
@usfslk this was fixed in June - https://github.com/55sketch/gsx2json/commit/1a44f6957d7366e23f5ca6a42c34ed59975e1562

Pull latest master if you are self hosting :)
