### ISSUE TITLE
gsx2json.com returns null on any spreadsheet

### ISSUE THREAD

**Issue by eboblin** [55sketch/gsx2json#17]
Even the one mentioned on site.

**Comment by ahmadkeren** [comment]
Any solution?

**Comment by PostmanZero** [comment]
Even changing to a new link v4 doesn't help, still null 🤔

**Comment by ismaelheinen** [comment]
Same here, all tests returning null

**Comment by eboblin** [comment]
The url that is being composed inside for grabbing "complex" json no longer works. It seems google changed that url

**Comment by themanjotsingh** [comment]
Google has made some changes to how it serves JSON and I think is also requiring authenticaion. I've made some changes and it seems to be working. You'll need to get your own API Key for authentication. https://github.com/themanjotsingh/gsx2json

Seems to be working for me. Hopefully someone more proficient can also take a look at the changes I've made and verify and then merge

**Comment by eboblin** [comment]
@themanjotsingh checked and it's working, thanks
Another change i had to figure out is that you can't get sheet by it's idx (starting with 1). Now you need to provide sheet's name. That should also be reflected in readme

**Comment by themanjotsingh** [comment]
@eboblin In my fork, I do have it written as sheetname instead of number as it was before. I'll make it more clear by adding a line regarding the change.

**Comment by 55sketch** [comment]
Thanks @themanjotsingh I'll review this now and get it merged 🙏

**Comment by themanjotsingh** [comment]
@55sketch Awesome, Thanks! 🙏

**Comment by 55sketch** [comment]
This has been resolved in both open source and hosted versions. I am already seeing us hit rate limits, so even if using the hosted version I would **strongly strongly strongly** suggest getting your own API key. In future I may enforce the API key as required.
