### ISSUE TITLE
"No entries returned. Do you have the right ID?"

### ISSUE THREAD

**Issue by marinagallardo** [55sketch/gsx2json#20]
I was using gsx2json for production, hosted in an Heroku app, and the app is not longer getting the sheet entries. I've read that API changed so I updated the files.

1. I've read here that Google API changed, so I made a new project clone and added the API key.
2. My ID is fine, I've test the gsx2json server to compare, and it works fine there but not in my Heroku own serve.

Always getting the same message: "No entries returned. Do you have the right ID?" Same ID works fine at gsx2json server. Please, can you give me some light to fix this issue?

**Comment by marinagallardo** [comment]
It was a issue related to Google Service config.

**Comment by 55sketch** [comment]
Thanks @marinagallardo - is the config issue something you think is worth documenting in the project?
