### ISSUE TITLE
Total number of sheets in a document so I can iterate over it?

### ISSUE THREAD

**Issue by VirenMohindra** [55sketch/gsx2json#3]
Is there a way to find the # of sheets in a document so I can possibly iterate over it to ingest all the sheets as json instead of using a loop and switching out the `sheet_number`?

**Comment by SaladDays831** [comment]
@VirenMohindra did you find a solution to this? I'm currently looking to do the same thing

**Comment by VirenMohindra** [comment]
@SaladDays831 I accounted for the number of the sheets in the document and then looped over them.
